web/authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.log_into_site, name='log_into_site'),
    path('logout', views.logout_of_site, name='logout_of_site'),
    path('register', views.register, name='register')
]

web/mealplanner/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('weekplanner/', include('weekplanner.urls')),
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
]

web/weekplanner/urls.py
from django.urls import path

from . import views

app_name="weekplanner"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:recipe_id>/edit', views.edit, name='edit'),
    path('<int:recipe_id>/delete', views.delete, name='delete'),
    path('submitchanges/', views.submit_changes, name='submit_changes'),
    path('<int:recipe_id>/', views.detail, name='detail'),
    path('addrecipe/', views.add_recipe, name='add_recipe'),
    path('random/', views.random_recipe, name='random_recipe'),
   
    path('tags/', views.tag_index, name='tag_index'),
    path('addtag/', views.add_tag, name='add_tag'),
    path('submittag/', views.submit_tag, name='submit_tag')
]

web/authentication/models.py
from django.db import models

# Create your models here.

web/weekplanner/models.py
from django.db import models

class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    user = models.CharField(max_length=300, null=False)
    def __str__(self):
        return self.name

class Recipe(models.Model):
    name = models.CharField(max_length=300, null=False, blank=False)
    duration = models.IntegerField()
    url = models.CharField(max_length=400)
    description = models.TextField()
    pub_date = models.DateTimeField('date published')
    user = models.CharField(max_length=300, null=False)
    tags = models.ManyToManyField(Tag)
    def __str__(self):
        return self.name

web/authentication/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse

import logging
logger = logging.getLogger("docker.console")



def index(request):
    return render(request, 'authentication/login.html')

def log_into_site(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/weekplanner');
    else:
        return render(request, 'authentication/login.html', {'error': 'Login failed, user not found or password incorrect'});

def register(request, error = ""):
    if(request.method == "GET"):
        return render(request, 'authentication/register.html')
    post = request.POST
    username = post['username']
    password = post['password']
    confirm = post['confirm']

    if(password != confirm):
        logger.info('passwords do not match')
        return render(request, 'authentication/register.html', {'error': 'Passwords do not match'})

    if(len(password) < 7):
        logger.info('password too short')
        return render(request, 'authentication/register.html', {'error': 'Password is too short'})

    newUser = User.objects.create_user(username, username, password)
    newUser.save()
    return render(request, 'authentication/login.html', {'notification': 'Successfully registered'})

def logout_of_site(request):
    logout(request)
    return render(request, 'authentication/login.html', {'notification': 'Successfully logged out'})

web/weekplanner/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from pprint import pprint
import logging, datetime, random
logger = logging.getLogger("docker.console")

from .models import Recipe, Tag

@login_required
def index(request):
    current_user = request.user
    latest_recipe_list = Recipe.objects.filter(user = current_user)
    latest_recipe_list = latest_recipe_list.order_by('name')
    context = {
        'latest_recipe_list': latest_recipe_list,
    }
    return render(request, 'recipes/index.html', context)

@login_required
def detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    logger.info("Details")
    logger.info(recipe);
    return render(request, 'recipes/detail.html', {'recipe': recipe})

@login_required
def add_recipe(request):
    logger.info("Adding recipe")
    user_tags = Tag.objects.filter(user=request.user)
    return render(request, 'recipes/add.html', {'tag_list': user_tags})

@login_required
def edit(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    logger.info("Editing recipe")
    logger.info(recipe)
    user_tags = Tag.objects.filter(user=request.user)
    recipe_tags = recipe.tags.all()
    return render(request, 'recipes/edit.html', {'recipe': recipe, 'recipe_tags': recipe_tags, 'tag_list': user_tags})

@login_required
def submit_changes(request):
    logger.info("submitting changes")
    post = request.POST
    recipe_id = post.get('id')
    current_user = request.user
    user_tags = Tag.objects.filter(user=request.user)
    
    if recipe_id is not None:
        logger.info('id found')
        recipe = get_object_or_404(Recipe, pk=recipe_id)
    else:
        logger.info('no id found')
        now = datetime.datetime.now()
        recipe = Recipe(pub_date = now, user = current_user)

    # Remove all tags and then add the ones
    recipe.tags.clear()
    for field in post:
        if 'tag_' in field:
            logger.info(field)
            tag_name = field.replace('tag_', '')
            tag_object = user_tags.filter(name=tag_name)[0]
            recipe.tags.add(tag_object)
    
    recipe.name = post.get('name')
    recipe.duration = post.get('duration')
    recipe.url = post.get('url')
    recipe.description = post.get('description')
    recipe.save()

    return HttpResponseRedirect(reverse('weekplanner:index'))

@login_required
def delete(request, recipe_id):
    logger.info("deleting recipe id")
    logger.info(recipe_id)
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    recipe.delete()
    return HttpResponseRedirect(reverse('weekplanner:index'), {'notification': 'Object successfully deleted'})

@login_required
def random_recipe(request):
    logger.info("random recipe being picked")
    current_user = request.user
    user_recipes = Recipe.objects.filter(user = current_user)
    logger.info(user_recipes)
    random_recipe = random.choice(user_recipes)
    return render(request, 'recipes/detail.html', {'recipe': random_recipe})

# Tag views

@login_required
def tag_index(request):
    current_user = request.user
    user_tags = Tag.objects.filter(user=current_user)
    return render(request, 'tags/index.html', {'tag_list': user_tags})

@login_required
def add_tag(request):
    return render(request, 'tags/add.html')

@login_required
def submit_tag(request):
    post = request.POST
    current_user = request.user
    tag_name = post.get('name')
    tag = Tag(user = current_user, name = tag_name)
    tag.save()
    return HttpResponseRedirect(reverse('weekplanner:index'), {'notification' : 'Tag successfully created'})

web/authentication/templates/authentication/login.html
{% load sass_tags %}

<link href="{% sass_src 'scss/test.scss' %}" rel="stylesheet" type="text/css" />

<h1>Welcome to Meal Planner. Please log in.</h1>

{% if notification is not None %}
<p class="notification">{{ notification }}</p>
{% endif %}

{% if error is not None %}
<p class="error">{{ error }}</p>
{% endif %}

<form action="{% url 'authentication:log_into_site' %}" method="post">
  {% csrf_token %}
  <label for="username">Email:</label>
  <input type="text" name="username" id="username" />
  <label for="password">Password:</label>
  <input type="password" name="password" id="password" />

  <input type="submit" value="login"/>
</form>

<a href="{% url 'authentication:register' %}">Register</a>

web/authentication/templates/authentication/register.html
<h1>Enter your details to use this dope webservice</h1>

{% if error %}
  <p>{{ error }}</p>
{% endif %}

<form action="{% url 'authentication:register' %}" method="post">
  {% csrf_token %}
  <label for="username">Email:</label>
  <input type="text" name="username" id="username" />
  <p>Please use a password with 8 or more characters</p>
  <label for="password">Password:</label>
  <input type="password" name="password" id="password" />
  <label for="confirm">Confirm password:</label>
  <input type="password" name="confirm" id="confirm" />

  <input type="submit" value="register"/>
</form>

web/weekplanner/templates/recipes/add.html
<h1>{{recipe.recipe_name}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'weekplanner:submit_changes' %}" method="post" id="submissionform">
  {% csrf_token %}
  <label for="name">Recipe name:</label>
  <input type="text" name="name" id="name" value=""/>

  <label for="duration">Duration (min):</label>
  <input type="number" name="duration" id="duration" value="0"/>

  <label for="url">URL:</label>
  <input type="text" name="url" id="url" value=""/>

  <label for="description">Description/notes:</label>
  <textarea form="submissionform" name="description" id="description"></textarea>

  {% for tag in tag_list %}
    <label for="tag{{forloop.counter}}">{{tag.name}}</label>
    <input type="checkbox" name="tag_{{tag.name}}" id="tag{{forloop.counter}}"/>
  {% endfor %}

  <input type="submit" value="add"/>
</form>

web/weekplanner/templates/recipes/detail.html
<h1>{{recipe.recipe_name}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<div class="row">
    <p>Recipe name:<p>
    <p>{{ recipe.name }}</p>
</div>

<div class="row">
    <p>Duration:<p>
    <p>{{ recipe.duration }}</p>
</div>

<div class="row">
    <p>URL:</p>
    <p>{{ recipe.url }}</p>
</div>

<div class="row">
    <p>Description:</p>
    <p>{{ recipe.description }}</p>
</div>

<div class="row">
    <p>Tags:</p>
    {% for tag in recipe.tags.all %}
        <p>{{tag.name}}</p>
    {% endfor %}
</div>

<a href="{% url 'weekplanner:edit' recipe.id %}">Edit recipe</a>
<a href="{% url 'weekplanner:delete' recipe.id %}">Delete recipe</a>

web/weekplanner/templates/recipes/edit.html
<h1>{{recipe.recipe_name}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'weekplanner:submit_changes' %}" method="post" id="submissionform">
  {% csrf_token %}
  <input type="hidden" name="id" id="id" value="{{recipe.id}}">
  
  <label for="name">Recipe name:</label>
  <input type="text" name="name" id="name" value="{{recipe.name}}"/>
  
  <label for="duration">Duration (min):</label>
  <input type="number" name="duration" id="duration" value="{{recipe.duration}}"/>

  <label for="url">URL:</label>
  <input type="text" name="url" id="url" value="{{recipe.url}}"/>

  <label for="description">Description/notes:</label>
  <textarea form="submissionform" name="description" id="description">{{recipe.description}}</textarea>

  {% for tag in tag_list %}
    <label for="tag{{forloop.counter}}">{{tag.name}}</label>
    {% if tag in recipe_tags %}
        <input type="checkbox" name="tag_{{tag.name}}" id="tag{{forloop.counter}}" checked/>
    {% else %}
        <input type="checkbox" name="tag_{{tag.name}}" id="tag{{forloop.counter}}"/>
    {% endif %}
  {% endfor %}

  <input type="submit" value="edit"/>
</form>

web/weekplanner/templates/recipes/index.html
{% if latest_recipe_list %}
    <ul>
    {% for recipe in latest_recipe_list %}
        <li><a href="{% url 'weekplanner:detail' recipe.id %}">{{ recipe.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recipes are available.</p>
{% endif %}
<a href="{% url 'weekplanner:add_recipe' %}">Add a recipe</a>
<a href="{% url 'weekplanner:random_recipe' %}">Get a random recipe</a>
<a href="{% url 'weekplanner:tag_index' %}">View all tags</a>
<a href="{% url 'weekplanner:add_tag' %}">Add a tag</a>

web/weekplanner/templates/tags/add.html
<h1>Adding tag</h1>

{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'weekplanner:submit_tag' %}" method="post" >
    {% csrf_token %}
    <label for="name">Tag name:</label>
    <input type="text" name="name" id="name" value=""/>

    <input type="submit" value="add"/>
</form>

web/weekplanner/templates/tags/index.html
{% if tag_list %}
    <ul>
    {% for tag in tag_list %}
        <li>{{ tag.name }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No tags created yet</p>
{% endif %}